spring:
  application:
    name: vets-service
  cache:
    cache-names: vets
# https://docs.spring.io/spring-cloud-config/docs/3.0.0/reference/html/#config-data-import
#config:
#    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://${CONFIG_SERVER_URL}:8888
---
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/manage"
      exposure: # https://docs.spring.io/spring-boot/docs/2.6.3/reference/html/actuator.html#actuator.endpoints.exposing
        include: "health,info,startup,env,mappings,metrics" # "*"
        exclude: "beans"    
  endpoint:
    health:
      enabled: true
      status:
        http-mapping:
          down: 503
          fatal: 503
          out-of-service: 503
      group:
        readiness:
          include: "readinessState"
        liveness:
          include: "livenessState"
    startup: # https://docs.spring.io/spring-boot/docs/2.6.6/reference/html/actuator.html#actuator.endpoints.kubernetes-probes
      enabled: true           
    probes:
        enabled: true      
    info:
      enabled: true
    env:
      enabled: true
    mappings:
      enabled: true            
  server:
    port: 8081
---