apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing-petclinic-ui
spec:
  rules:
  - host: $ING_HOST # petclinic.<public-IP>.nip.io
    http:
      paths:
      - backend:
          serviceName: ui-service
          servicePort: 80
        path: /
      - backend:
          serviceName: ui-service
          servicePort: 80
        path: /manage/health
      - backend:
          serviceName: ui-service
          servicePort: 80
        path: /manage/info