apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-petclinic-admin-server
  annotations:
      service.beta.kubernetes.io/azure-dns-label-name: $DNS_LABEL # petclinic-admin-aks-xxx.cloudapp.azure.com
      # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  rules:
  - host: $ING_HOST # petclinic-admin-aks-xxx.northeurope.cloudapp.azure.com petclinic.<public-IP>.nip.io
    http:
      paths:
      - backend:
          serviceName: admin-server
          servicePort: 9090
        path: /admin-server
      - backend:
          serviceName: admin-server
          servicePort: 9090
        path: /manage/health
      - backend:
          serviceName: admin-server
          servicePort: 9090
        path: /manage/info