# https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access
# https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/usage/
# https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/examples/keyvault-secrets/v1alpha1_secretproviderclass_secrets.yaml
# https://github.com/Azure/fta-java-openhack/blob/main/challenges/aks/04_openlab_secrets_aks.md
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ${SECRET_PROVIDER_CLASS_NAME} # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: ${USER_ASSIGNED_CLIENT_ID} # Setting this to use workload identity
    keyvaultName: ${KEYVAULT_NAME}       # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SPRING-CLOUD-AZURE-TENANT-ID
          objectAlias: tenantid
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SPRING-DATASOURCE-PASSWORD
          objectType: secret              # object types: secret, key, or cert
          objectAlias: dbpassword          
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: ${IDENTITY_TENANT}        # The tenant ID of the key vault