# This workflow will deploy all the Azure services, including AKS, KV & secrets, MYSQL (eventually with a Firewall rule to allow your workstation IP)
# eventually if DEPLOY_TO_VNET is set to true : also VNet, AKS deployed to VNet, private DNS-Zone, client VM deployed to the VNet

name: Deploy IaC with Azure Bicep

env:
  APP_NAME: petcliaks
  LOCATION: westeurope # francecentral
  RG_KV: rg-iac-kv33 # RG where to deploy KV
  RG_APP: rg-iac-aks-petclinic-mic-srv # RG where to deploy the other Azure services: AKS, ACR, MySQL, etc.
  
  ACR_NAME: acrpetcliaks
  DNS_ZONE: cloudapp.azure.com
  APP_DNS_ZONE: petclinic.westeurope.cloudapp.azure.com
  CUSTOM_DNS: javaonazurehandsonlabs.com

  AKS_CLUSTER_NAME: aks-petcliaks

  VNET_NAME: vnet-aks
  VNET_CIDR: 172.16.0.0/16
  AKS_SUBNET_CIDR: 172.16.1.0/24
  AKS_SUBNET_NAME: snet-aks

  DNS_PREFIX: appinnojava
  ING_NS: ingress # Namespace to use for the Ingress Controller
  AKS_IDENTITY_NAME: id-aks-cluster-dev-westeurope-101

  START_IP_ADDRESS: 172.16.1.0
  END_IP_ADDRESS: 172.16.1.255
  CLIENT_IP_ADDRESS: 42.42.42.42 #  not used

  MYSQL_SERVER_NAME: petcliaks
  MYSQL_DB_NAME: petclinic
  MYSQL_ADM_USR: mys_adm
  MYSQL_TIME_ZONE: Europe/Paris
  MYSQL_CHARACTER_SET: utf8
  MYSQL_PORT: 3306

  DEPLOY_TO_VNET: false

  KV_NAME: kv-petcliaks33 # The name of the KV, must be UNIQUE. A vault name must be between 3-24 alphanumeric characters
  SET_KV_ACCESS_POLICIES: false # let it to false

  # GIT_CFG_URI: https://github.com/ezYakaEagle442/aks-cfg-srv

  VM_ADMIN_USER_NAME: adm_aks
  
  # https://github.com/Azure/actions-workflow-samples/blob/master/assets/create-secrets-for-GitHub-workflows.md#consume-secrets-in-your-workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-secrets

  # ==== Secrets ====

  # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
  # Never use structured data as a secret
  # Structured data can cause secret redaction within logs to fail, because redaction largely relies on finding an exact match for 
  # the specific secret value. For example, do not use a blob of JSON, XML, or YAML (or similar) to encapsulate a secret value, 
  # as this significantly reduces the probability the secrets will be properly redacted. Instead, create individual secrets for each sensitive value.

  SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

  SPRING_CLOUD_AZURE_KEY_VAULT_ENDPOINT: ${{ secrets.SPRING_CLOUD_AZURE_KEY_VAULT_ENDPOINT }}
  SPRING_CLOUD_AZURE_TENANT_ID: ${{ secrets.SPRING_CLOUD_AZURE_TENANT_ID }}
  
  VM_ADMIN_PASSWORD: ${{ secrets.VM_ADMIN_PASSWORD }}

  SSH_PRV_KEY: ${{ secrets.SSH_PRV_KEY }}
  SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
  SSH_KEY: aksadm

  # https://learn.microsoft.com/en-us/azure/key-vault/secrets/secrets-best-practices#secrets-rotation
  # Because secrets are sensitive to leakage or exposure, it's important to rotate them often, at least every 60 days. 
  # Expiry date in seconds since 1970-01-01T00:00:00Z. Ex: 1672444800 ==> 31/12/2022'
  SECRET_EXPIRY_DATE: 1703980800 # ==> 31/12/2023

  credentials: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # ==== Versions ====
  DEPLOYMENT_VERSION: 2.6.13
  AZ_CLI_VERSION: 2.42.0
  JAVA_VERSION: 11

on:
  workflow_dispatch:

jobs:
 
  call-pre-req-workflow:
    name: Trigger Pre-Req
    uses: ./.github/workflows/deploy-iac-pre-req.yml
    secrets: inherit

  deploy-iac:
    needs: call-pre-req-workflow
    runs-on: ubuntu-latest
            
    steps:
    - name: Login with GHA Runner SP
      uses: azure/login@v1.4.6 # fails https://github.com/marketplace/actions/azure-login
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # ${{ env.credentials }}

    - name: Checkout
      uses: actions/checkout@v3 # https://github.com/actions/checkout

    - name: Create AKS cluster
      run: |
          echo "****************************************************************************************"
          echo "*                                                                                      *"
          echo "*                                                                                      *"
          echo "*About to create AKS cluster                                                           *"
          echo "*                                                                                      *"         
          echo "*                                                                                      *"
          echo "****************************************************************************************"

          az deployment group create --name aks-petclinic-main -f iac/bicep/main.bicep -g ${{ env.RG_APP }} \
            -p appName=${{ env.APP_NAME }} \
            -p location=${{ env.LOCATION }} \
            -p kvName=${{ env.KV_NAME }} \
            -p kvRGName=${{ env.RG_KV }} \
            -p publicNetworkAccess=enabled \
            -p startIpAddress=${{ env.START_IP_ADDRESS }} \
            -p endIpAddress=${{ env.END_IP_ADDRESS }} \
            -p clientIPAddress=${{ env.CLIENT_IP_ADDRESS }} \
            -p vnetName=${{ env.VNET_NAME }} \
            -p subnetName=${{ env.AKS_SUBNET_NAME }} \
            -p vnetCidr=${{ env.VNET_CIDR }} \
            -p dnsPrefix=${{ env.DNS_PREFIX }} \
            -p aksIdentityName=${{ env.AKS_IDENTITY_NAME }} \
            -p mySQLServerName=${{ env.MYSQL_SERVER_NAME }} \
            -p mySQLadministratorLogin=${{ env.MYSQL_ADM_USR }} \
            -p mySQLadministratorLoginPassword=${{ env.SPRING_DATASOURCE_PASSWORD }} \
            -p acrName=${{ env.ACR_NAME }} \
            -p sshPublicKey="${{ env.SSH_PUB_KEY }}"
 

      shell: bash

    - name: Whitelist AKS OutboundIP
      run: |
            az config set extension.use_dynamic_install=yes_without_prompt

            echo "About to Whitelist AKS OutboundIP in KV & MySQL"

            vNetRules=$(az deployment group show --name vnet-aks \
              -g ${{ env.RG_APP }} \
              --query properties.outputs.aksSubnetId.value)

            managed_rg=$(az aks show --resource-group ${{ env.RG_APP }} --name ${{ env.AKS_CLUSTER_NAME }} --query nodeResourceGroup -o tsv)
            echo "CLUSTER_RESOURCE_GROUP:" $managed_rg

            aksOutboundIPResourceId=$(az deployment group show --name aks-petclinic-main \
              -g ${{ env.RG_APP }} \
              --query properties.outputs.aksEffectiveOutboundIPs.value[0] | jq -r .id)
            
            aksOutboundIP=$(az network public-ip show --ids $aksOutboundIPResourceId --query ipAddress)
            echo "aksOutboundIP:" $aksOutboundIP

            ipRules=[$aksOutboundIP]

            az deployment group create --name aks-kv-mysql-set-ip-rules -f iac/bicep/set-ip-rules.bicep -g ${{ env.RG_APP }} \
              -p appName=${{ env.APP_NAME }} \
              -p location=${{ env.LOCATION }} \
              -p kvName=${{ env.KV_NAME }} \
              -p kvRGName=${{ env.RG_KV }} \
              -p mySQLadministratorLogin=${{ env.MYSQL_ADM_USR }} \
              -p mySQLServerName=${{ env.MYSQL_SERVER_NAME }} \
              -p vNetRules=[$vNetRules] \
              -p ipRules=$ipRules \
              -p setFwRuleClient=false \
              -p startIpAddress=${{ env.START_IP_ADDRESS }} \
              -p endIpAddress=${{ env.END_IP_ADDRESS }} \
              -p clientIPAddress=${{ env.CLIENT_IP_ADDRESS }}

      shell: bash

    # https://github.com/marketplace/actions/helm-tool-installer
    - name: setup HELM
      run: |
            # https://github.com/kubernetes/ingress-nginx
            # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
            # https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/
            # https://docs.microsoft.com/en-us/azure/aks/ingress-basic#create-an-ingress-controller 

            az aks get-credentials --name ${{ env.AKS_CLUSTER_NAME }} -g ${{ env.RG_APP }} --admin
            kubectl cluster-info
            
            helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
            helm repo update

            helm install ingress-nginx ingress-nginx/ingress-nginx \
              --create-namespace \
              --namespace ${{ env.ING_NS }} \
              --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz            
            
            helm ls --namespace ${{ env.ING_NS }}
            kubectl get deployments -n ${{ env.ING_NS }} -l app.kubernetes.io/name=ingress-nginx

            ing_ctl_ip=$(kubectl get svc -n ${{ env.ING_NS }} ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[*].ip}")
            echo ing_ctl_ip" >> $GITHUB_ENV
      shell: bash

    - name: setup DNS
      run: |
            az deployment group create --name aks-dns -f iac/bicep/modules/aks/dns.bicep -g ${{ env.RG_APP }} \
              -p appDnsZone=${{ env.APP_DNS_ZONE }} \
              -p location=${{ env.LOCATION }} \
              -p vnetName=${{ env.VNET_NAME }} \
              -p aksSvcIp=$ing_ctl_ip

      shell: bash

    # security hardening for self-hosted agents: https://github.com/marketplace/actions/azure-login
    # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#hardening-for-self-hosted-runners
    # if the runner is self-hosted which is not github provided it is recommended to manually logout at the end of the workflow as shown below.
    - name: Azure Logout security hardening
      run: |
          az logout
          az cache purge
          az account clear
      shell: bash
      
  call-db-init-workflow:
    name: Load Data to DB
    needs: deploy-iac
    uses: ./.github/workflows/sql-load.yml
    secrets: inherit

  call-maven-build-workflow:
    name: Trigger Maven for backend services
    needs: deploy-iac
    uses: ./.github/workflows/maven-build.yml # .github/workflows/maven-build.yml@main ==> references to workflows must be prefixed with format 'owner/repository/' or './' for local workflows
    secrets: inherit # pass all secrets
      # envPAT: ${{ secrets.envPAT }} # pass just this secret

  call-maven-build-ui-workflow:
    name: Trigger Maven for the UI
    needs: deploy-iac
    uses: ./.github/workflows/maven-build-ui.yml
    secrets: inherit

  # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
  call-deploy-apps-svc-workflow:
    name: Trigger App Deployment for the Backend services
    needs: [deploy-iac, call-maven-build-workflow]
    uses: ./.github/workflows/deploy-app-svc.yml
    with:
      tag_id: ${{ needs.call-maven-build-workflow.outputs.tag_id }}
    secrets: inherit

  call-deploy-ui-workflow:
    name: Trigger UI Deployment
    needs:  [deploy-iac, call-maven-build-ui-workflow]
    uses: ./.github/workflows/deploy-app-ui.yml
    with:
      tag_id: ${{ needs.call-maven-build-ui-workflow.outputs.tag_id }}
    secrets: inherit

  logout:
    needs: [call-deploy-apps-svc-workflow, call-deploy-ui-workflow]
    runs-on: ubuntu-latest
    steps:    
    - name: Azure Logout security hardening
      run: |
          az logout
          az cache purge
          az account clear
      shell: bash